const credential = require('../src/credential');
const knex = require('knex')({
  client: 'mysql',
  connection: {
    host: credential.host,
    user: credential.user,
    password: credential.pass,
    database: credential.db,
  },
});

const genres = [
  {
    id: 28,
    name: 'Action',
  },
  {
    id: 12,
    name: 'Adventure',
  },
  {
    id: 16,
    name: 'Animation',
  },
  {
    id: 35,
    name: 'Comedy',
  },
  {
    id: 80,
    name: 'Crime',
  },
  {
    id: 99,
    name: 'Documentary',
  },
  {
    id: 18,
    name: 'Drama',
  },
  {
    id: 10751,
    name: 'Family',
  },
  {
    id: 14,
    name: 'Fantasy',
  },
  {
    id: 36,
    name: 'History',
  },
  {
    id: 27,
    name: 'Horror',
  },
  {
    id: 10402,
    name: 'Music',
  },
  {
    id: 9648,
    name: 'Mystery',
  },
  {
    id: 10749,
    name: 'Romance',
  },
  {
    id: 878,
    name: 'Science Fiction',
  },
  {
    id: 10770,
    name: 'TV Movie',
  },
  {
    id: 53,
    name: 'Thriller',
  },
  {
    id: 10752,
    name: 'War',
  },
  {
    id: 37,
    name: 'Western',
  },
];
const movies = [
  {
    vote_count: 731,
    id: 19404,
    video: false,
    vote_average: 9.1,
    title: 'Dilwale Dulhania Le Jayenge',
    popularity: 42.172585,
    poster_path: '/2gvbZMtV1Zsl7FedJa5ysbpBx2G.jpg',
    original_language: 'hi',
    original_title: 'Dilwale Dulhania Le Jayenge',
    genre_ids: [35, 18, 10749],
    backdrop_path: '/nl79FQ8xWZkhL3rDr1v2RFFR6J0.jpg',
    adult: false,
    overview:
      'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
    release_date: '1995-10-20',
  },
  {
    vote_count: 8527,
    id: 278,
    video: false,
    vote_average: 8.5,
    title: 'The Shawshank Redemption',
    popularity: 60.380278,
    poster_path: '/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg',
    original_language: 'en',
    original_title: 'The Shawshank Redemption',
    genre_ids: [18, 80],
    backdrop_path: '/xBKGJQsAIeweesB79KC89FpBrVr.jpg',
    adult: false,
    overview:
      'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
    release_date: '1994-09-23',
  },
  {
    vote_count: 1137,
    id: 372058,
    video: false,
    vote_average: 8.5,
    title: 'Your Name.',
    popularity: 53.222773,
    poster_path: '/xq1Ugd62d23K2knRUx6xxuALTZB.jpg',
    original_language: 'ja',
    original_title: '君の名は。',
    genre_ids: [10749, 16, 18],
    backdrop_path: '/7OMAfDJikBxItZBIug0NJig5DHD.jpg',
    adult: false,
    overview:
      'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
    release_date: '2016-08-26',
  },
  {
    vote_count: 6189,
    id: 238,
    video: false,
    vote_average: 8.5,
    title: 'The Godfather',
    popularity: 50.796858,
    poster_path: '/rPdtLWNsZmAtoZl9PK7S2wE3qiS.jpg',
    original_language: 'en',
    original_title: 'The Godfather',
    genre_ids: [18, 80],
    backdrop_path: '/6xKCYgH16UuwEGAyroLU6p8HLIn.jpg',
    adult: false,
    overview:
      'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
    release_date: '1972-03-14',
  },
  {
    vote_count: 75,
    id: 414419,
    video: false,
    vote_average: 8.5,
    title: 'Kill Bill: The Whole Bloody Affair',
    popularity: 8.988042,
    poster_path: '/cMmicZ9yi69pctF5byT6QZMrmj.jpg',
    original_language: 'en',
    original_title: 'Kill Bill: The Whole Bloody Affair',
    genre_ids: [80, 28],
    backdrop_path: '/lCQ5SxicnUrTpRHgeueD1HLhst4.jpg',
    adult: false,
    overview:
      "Kill Bill: The Whole Bloody affair is a complete edit of the two part martial arts action films Kill Bill: Volume 1 and Kill Bill: Volume 2. The film was originally scheduled to be released as one part. However, due to the film's over 4 hour running time, it was split into two parts.",
    release_date: '2011-03-28',
  },
  {
    vote_count: 4588,
    id: 424,
    video: false,
    vote_average: 8.3,
    title: "Schindler's List",
    popularity: 47.253464,
    poster_path: '/yPisjyLweCl1tbgwgtzBCNCBle.jpg',
    original_language: 'en',
    original_title: "Schindler's List",
    genre_ids: [18, 36, 10752],
    backdrop_path: '/rIpSszng8P0DL0TimSzZbpfnvh1.jpg',
    adult: false,
    overview:
      'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
    release_date: '1993-11-29',
  },
  {
    vote_count: 4127,
    id: 129,
    video: false,
    vote_average: 8.3,
    title: 'Spirited Away',
    popularity: 47.589461,
    poster_path: '/dL11DBPcRhWWnJcFXl9A07MrqTI.jpg',
    original_language: 'ja',
    original_title: '千と千尋の神隠し',
    genre_ids: [16, 10751, 14],
    backdrop_path: '/mnpRKVSXBX6jb56nabvmGKA0Wig.jpg',
    adult: false,
    overview:
      'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
    release_date: '2001-07-20',
  },
  {
    vote_count: 3525,
    id: 240,
    video: false,
    vote_average: 8.3,
    title: 'The Godfather: Part II',
    popularity: 38.251472,
    poster_path: '/bVq65huQ8vHDd1a4Z37QtuyEvpA.jpg',
    original_language: 'en',
    original_title: 'The Godfather: Part II',
    genre_ids: [18, 80],
    backdrop_path: '/gLbBRyS7MBrmVUNce91Hmx9vzqI.jpg',
    adult: false,
    overview:
      'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
    release_date: '1974-12-20',
  },
  {
    vote_count: 184,
    id: 455661,
    video: false,
    vote_average: 8.3,
    title: 'In a Heartbeat',
    popularity: 37.456203,
    poster_path: '/wJUJROdLOtOzMixkjkx1aaZGSLl.jpg',
    original_language: 'en',
    original_title: 'In a Heartbeat',
    genre_ids: [10751, 16, 10749, 35],
    backdrop_path: '/4datX8btikWEikf7esqEe6fhw.jpg',
    adult: false,
    overview:
      'A closeted boy runs the risk of being outed by his own heart after it pops out of his chest to chase down the boy of his dreams.',
    release_date: '2017-06-01',
  },
  {
    vote_count: 4507,
    id: 244786,
    video: false,
    vote_average: 8.3,
    title: 'Whiplash',
    popularity: 97.22628,
    poster_path: '/lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg',
    original_language: 'en',
    original_title: 'Whiplash',
    genre_ids: [18],
    backdrop_path: '/6bbZ6XyvgfjhQwbplnUh1LSj1ky.jpg',
    adult: false,
    overview:
      'Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.',
    release_date: '2014-10-10',
  },
  {
    vote_count: 77,
    id: 38288,
    video: false,
    vote_average: 8.3,
    title: 'I Corti',
    popularity: 6.89386,
    poster_path: '/82KeyiTv5lyfz4K2KzokXJrn7kR.jpg',
    original_language: 'it',
    original_title: 'I Corti',
    genre_ids: [],
    backdrop_path: '/y1YrEQazmKcEKgMi4w0JqxxssGX.jpg',
    adult: false,
    overview:
      "The shorts of Aldo , Giovanni &amp; Giacomo was the first theatrical show of the trio of comedians Aldo , Giovanni &amp; Giacomo , with the participation of Marina Massironi .  The show is the son of the fortunate trio 's holdings in television as Mai dire Gol, and shows such as The Circus by Paolo Rossi and on the head !  The short was recorded live at the Teatro Nuovo in Ferrara on 28 and 29 March 1996. Produced by Agidi , the theater director is entrusted to the change artist Arturo Brachetti .",
    release_date: '1996-01-01',
  },
  {
    vote_count: 132,
    id: 40096,
    video: false,
    vote_average: 8.3,
    title: "A Dog's Will",
    popularity: 15.980853,
    poster_path: '/uHEmM49YphluJnGep8Ef1qwD2QX.jpg',
    original_language: 'pt',
    original_title: 'O Auto da Compadecida',
    genre_ids: [12, 35, 18],
    backdrop_path: '/alQqTpmEkxSLgajfEYTsTH6nAKB.jpg',
    adult: false,
    overview:
      'The lively João Grilo and the sly Chicó are poor guys living in the hinterland who cheat a bunch of people in a small Northeast Brazil town. But when they die, they have to be judged by Christ, the Devil and the Virgin Mary, before they are admitted to paradise.',
    release_date: '2000-09-10',
  },
  {
    vote_count: 9979,
    id: 550,
    video: false,
    vote_average: 8.3,
    title: 'Fight Club',
    popularity: 51.505677,
    poster_path: '/adw6Lq9FiC9zjYEpOqfq03ituwp.jpg',
    original_language: 'en',
    original_title: 'Fight Club',
    genre_ids: [18],
    backdrop_path: '/8uO0gUM8aNqYLs1OsTBQiXu0fEv.jpg',
    adult: false,
    overview:
      'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
    release_date: '1999-10-15',
  },
  {
    vote_count: 3814,
    id: 637,
    video: false,
    vote_average: 8.3,
    title: 'Life Is Beautiful',
    popularity: 44.251797,
    poster_path: '/f7DImXDebOs148U4uPjI61iDvaK.jpg',
    original_language: 'it',
    original_title: 'La vita è bella',
    genre_ids: [35, 18],
    backdrop_path: '/bORe0eI72D874TMawOOFvqWS6Xe.jpg',
    adult: false,
    overview:
      'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.',
    release_date: '1997-12-20',
  },
  {
    vote_count: 2518,
    id: 539,
    video: false,
    vote_average: 8.3,
    title: 'Psycho',
    popularity: 37.209277,
    poster_path: '/81d8oyEFgj7FlxJqSDXWr8JH8kV.jpg',
    original_language: 'en',
    original_title: 'Psycho',
    genre_ids: [18, 27, 53],
    backdrop_path: '/3md49VBCeqY6MSNyAVY6d5eC6bA.jpg',
    adult: false,
    overview:
      'When larcenous real estate clerk Marion Crane goes on the lam with a wad of cash and hopes of starting a new life, she ends up at the notorious Bates Motel, where manager Norman Bates cares for his housebound mother. The place seems quirky, but fine… until Marion decides to take a shower.',
    release_date: '1960-06-16',
  },
  {
    vote_count: 8985,
    id: 680,
    video: false,
    vote_average: 8.3,
    title: 'Pulp Fiction',
    popularity: 187.671559,
    poster_path: '/dM2w364MScsjFf8pfMbaWUcWrR.jpg',
    original_language: 'en',
    original_title: 'Pulp Fiction',
    genre_ids: [53, 80],
    backdrop_path: '/9rZg1J6vMQoDVSgRyWcpJa8IAGy.jpg',
    adult: false,
    overview:
      "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    release_date: '1994-09-10',
  },
  {
    vote_count: 3109,
    id: 510,
    video: false,
    vote_average: 8.3,
    title: "One Flew Over the Cuckoo's Nest",
    popularity: 40.947268,
    poster_path: '/2Sns5oMb356JNdBHgBETjIpRYy9.jpg',
    original_language: 'en',
    original_title: "One Flew Over the Cuckoo's Nest",
    genre_ids: [18],
    backdrop_path: '/4E7YQcwui0PfNXguf4V2X8YocPC.jpg',
    adult: false,
    overview:
      'While serving time for insanity at a state mental hospital, implacable rabble-rouser, Randle Patrick McMurphy inspires his fellow patients to rebel against the authoritarian rule of head nurse, Mildred Ratched.',
    release_date: '1975-11-18',
  },
  {
    vote_count: 258,
    id: 374430,
    video: false,
    vote_average: 8.3,
    title: 'Black Mirror: White Christmas',
    popularity: 37.123775,
    poster_path: '/he609rnU3tiwBjRklKNa4n2jQSd.jpg',
    original_language: 'en',
    original_title: 'Black Mirror: White Christmas',
    genre_ids: [18, 27, 9648, 878, 53, 10770],
    backdrop_path: '/rMCew7St2vy9iV3QOPzx15sAkFJ.jpg',
    adult: false,
    overview:
      "This feature-length special consists of three interwoven stories. In a mysterious and remote snowy outpost, Matt and Potter share a Christmas meal, swapping creepy tales of their earlier lives in the outside world. Matt is a charismatic American trying to bring the reserved, secretive Potter out of his shell. But are both men who they appear to be? A woman gets thrust into a nightmarish world of 'smart' gadgetry. Plus a look at what would happen if you could 'block' people in real life.",
    release_date: '2014-12-16',
  },
  {
    vote_count: 12529,
    id: 155,
    video: false,
    vote_average: 8.3,
    title: 'The Dark Knight',
    popularity: 67.56648,
    poster_path: '/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg',
    original_language: 'en',
    original_title: 'The Dark Knight',
    genre_ids: [18, 28, 80, 53],
    backdrop_path: '/hqkIcbrOHL86UncnHIsHVcVmzue.jpg',
    adult: false,
    overview:
      'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
    release_date: '2008-07-16',
  },
  {
    vote_count: 1153,
    id: 311,
    video: false,
    vote_average: 8.3,
    title: 'Once Upon a Time in America',
    popularity: 33.144553,
    poster_path: '/fqP3Q7DWMFqW7mh11hWXbNwN9rz.jpg',
    original_language: 'en',
    original_title: 'Once Upon a Time in America',
    genre_ids: [18, 80],
    backdrop_path: '/vnT6HzjLSDrAweHn9xWykb8Ii6T.jpg',
    adult: false,
    overview:
      'A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later, where he once again must confront the ghosts and regrets of his old life.',
    release_date: '1984-02-16',
  },
  {
    vote_count: 307,
    id: 313106,
    video: false,
    vote_average: 8.2,
    title: 'Doctor Who: The Day of the Doctor',
    popularity: 14.528646,
    poster_path: '/lQy2QVcacuH55k37K9Ox0gw3YpZ.jpg',
    original_language: 'en',
    original_title: 'Doctor Who: The Day of the Doctor',
    genre_ids: [878, 12],
    backdrop_path: '/8bxjRFqFztBoXdVEx6q2u66a0s1.jpg',
    adult: false,
    overview:
      "In 2013, something terrible is awakening in London's National Gallery; in 1562, a murderous plot is afoot in Elizabethan England; and somewhere in space an ancient battle reaches its devastating conclusion. All of reality is at stake as the Doctor's own dangerous past comes back to haunt him.",
    release_date: '2013-11-23',
  },
  {
    vote_count: 8407,
    id: 13,
    video: false,
    vote_average: 8.2,
    title: 'Forrest Gump',
    popularity: 36.289476,
    poster_path: '/yE5d3BUhE8hCnkMUJOo1QDoOGNz.jpg',
    original_language: 'en',
    original_title: 'Forrest Gump',
    genre_ids: [35, 18, 10749],
    backdrop_path: '/ctOEhQiFIHWkiaYp7b0ibSTe5IL.jpg',
    adult: false,
    overview:
      "A man with a low IQ has accomplished great things in his life and been present during significant historic events - in each case, far exceeding what anyone imagined he could do. Yet, despite all the things he has attained, his one true love eludes him. 'Forrest Gump' is the story of a man who rose above his challenges, and who proved that determination, courage, and love are more important than ability.",
    release_date: '1994-07-06',
  },
  {
    vote_count: 3288,
    id: 769,
    video: false,
    vote_average: 8.2,
    title: 'GoodFellas',
    popularity: 24.350375,
    poster_path: '/hAPeXBdGDGmXRPj4OZZ0poH65Iu.jpg',
    original_language: 'en',
    original_title: 'GoodFellas',
    genre_ids: [18, 80],
    backdrop_path: '/xDEOxA01480uLTWuvQCw61VmDBt.jpg',
    adult: false,
    overview:
      'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
    release_date: '1990-09-12',
  },
  {
    vote_count: 552,
    id: 599,
    video: false,
    vote_average: 8.2,
    title: 'Sunset Boulevard',
    popularity: 16.613935,
    poster_path: '/oFwzvRgfxJc0FUr2mwYTi10dk3G.jpg',
    original_language: 'en',
    original_title: 'Sunset Boulevard',
    genre_ids: [18],
    backdrop_path: '/49OTCCPYlARRe2JS1PAhPJmFkIW.jpg',
    adult: false,
    overview:
      'A hack screenwriter writes a screenplay for a former silent-film star who has faded into Hollywood obscurity.',
    release_date: '1950-08-10',
  },
  {
    vote_count: 4324,
    id: 497,
    video: false,
    vote_average: 8.2,
    title: 'The Green Mile',
    popularity: 29.111177,
    poster_path: '/3yJUlOtVa09CYJocwBU8eAryja0.jpg',
    original_language: 'en',
    original_title: 'The Green Mile',
    genre_ids: [14, 18, 80],
    backdrop_path: '/Rlt20sEbOQKPVjia7lUilFm49W.jpg',
    adult: false,
    overview:
      "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cellblock's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
    release_date: '1999-12-10',
  },
  {
    vote_count: 2178,
    id: 389,
    video: false,
    vote_average: 8.2,
    title: '12 Angry Men',
    popularity: 20.415597,
    poster_path: '/3W0v956XxSG5xgm7LB6qu8ExYJ2.jpg',
    original_language: 'en',
    original_title: '12 Angry Men',
    genre_ids: [18],
    backdrop_path: '/lH2Ga8OzjU1XlxJ73shOlPx6cRw.jpg',
    adult: false,
    overview:
      "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
    release_date: '1957-03-25',
  },
  {
    vote_count: 194,
    id: 18148,
    video: false,
    vote_average: 8.2,
    title: 'Tokyo Story',
    popularity: 16.176407,
    poster_path: '/mMlPycVtj0bYZvTBpHe5BpVBk2S.jpg',
    original_language: 'ja',
    original_title: '東京物語',
    genre_ids: [18],
    backdrop_path: '/m55rLpSklCkBmYhhLuZZhhesWFW.jpg',
    adult: false,
    overview:
      'An old couple visit their children and grandchildren in the city, but the children have little time for them.',
    release_date: '1953-11-03',
  },
  {
    vote_count: 164,
    id: 780,
    video: false,
    vote_average: 8.2,
    title: 'The Passion of Joan of Arc',
    popularity: 14.482599,
    poster_path: '/5HL0dEJfd7PF0eRiKz8BiNfe8Tf.jpg',
    original_language: 'fr',
    original_title: "La passion de Jeanne d'Arc",
    genre_ids: [18, 36],
    backdrop_path: '/hZuYH68nGqqUKZlOnxb8zjeR92U.jpg',
    adult: false,
    overview:
      "A classic of the silent age, this film tells the story of the doomed but ultimately canonized 15th-century teenage warrior. On trial for claiming she'd spoken to God, Jeanne d'Arc is subjected to inhumane treatment and scare tactics at the hands of church court officials. Initially bullied into changing her story, Jeanne eventually opts for what she sees as the truth. Her punishment, a famously brutal execution, earns her perpetual martyrdom.",
    release_date: '1928-04-21',
  },
  {
    vote_count: 160,
    id: 451945,
    video: false,
    vote_average: 8.2,
    title: '120 Beats Per Minute',
    popularity: 16.539811,
    poster_path: '/uyGiTEZDT1m4m2VM3piP9NoszV4.jpg',
    original_language: 'fr',
    original_title: '120 battements par minute',
    genre_ids: [18],
    backdrop_path: '/jsaD6llm7kpkS0qfcfLByCmqrub.jpg',
    adult: false,
    overview:
      'Paris, in the early 1990s: a group of young activists is desperately tied to finding the cure against an unknown lethal disease. They target the pharmaceutical labs that are retaining potential cures, and multiply direct actions, with the hope of saving their lives as well as the ones of future generations.',
    release_date: '2017-08-23',
  },
  {
    vote_count: 860,
    id: 11216,
    video: false,
    vote_average: 8.2,
    title: 'Cinema Paradiso',
    popularity: 14.650762,
    poster_path: '/xKAweeF2ZPMNn6ce4GclSbr59Pv.jpg',
    original_language: 'it',
    original_title: 'Nuovo Cinema Paradiso',
    genre_ids: [18, 10749],
    backdrop_path: '/tVi83ttAeyMJinYpy6xfgJSpzvP.jpg',
    adult: false,
    overview:
      "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
    release_date: '1988-11-17',
  },
  {
    vote_count: 6123,
    id: 1891,
    video: false,
    vote_average: 8.2,
    title: 'The Empire Strikes Back',
    popularity: 19.624504,
    poster_path: '/6u1fYtxG5eqjhtCPDx04pJphQRW.jpg',
    original_language: 'en',
    original_title: 'The Empire Strikes Back',
    genre_ids: [12, 28, 878],
    backdrop_path: '/amYkOxCwHiVTFKendcIW0rSrRlU.jpg',
    adult: false,
    overview:
      'The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.',
    release_date: '1980-05-17',
  },
  {
    vote_count: 127,
    id: 12493,
    video: false,
    vote_average: 8.2,
    title: 'High and Low',
    popularity: 14.406643,
    poster_path: '/tgNjemQPG96uIezpiUiXFcer5ga.jpg',
    original_language: 'ja',
    original_title: '天国と地獄',
    genre_ids: [9648, 18, 53, 80],
    backdrop_path: '/2xliq3zIrQPIWG66Fc0bgVoBUWc.jpg',
    adult: false,
    overview:
      "An executive of a shoe company becomes a victim of extortion when his chauffeur's son is kidnapped and held for ransom.",
    release_date: '1963-03-01',
  },
  {
    vote_count: 140,
    id: 14537,
    video: false,
    vote_average: 8.2,
    title: 'Harakiri',
    popularity: 21.418661,
    poster_path: '/99EyyBq5dXEvY37jF7EyERhQcFe.jpg',
    original_language: 'ja',
    original_title: '切腹',
    genre_ids: [28, 18, 36],
    backdrop_path: '/dT51Ul1GN5HSOVokDnnCk54VkdA.jpg',
    adult: false,
    overview:
      "Peace in 17th-century Japan causes the Shogunate's breakup of warrior clans, throwing thousands of samurai out of work and into poverty. An honorable end to such fate under the samurai code is ritual suicide, or hara-kiri.",
    release_date: '1962-09-15',
  },
  {
    vote_count: 2110,
    id: 128,
    video: false,
    vote_average: 8.2,
    title: 'Princess Mononoke',
    popularity: 21.097167,
    poster_path: '/gzlJkVfWV5VEG5xK25cvFGJgkDz.jpg',
    original_language: 'ja',
    original_title: 'もののけ姫',
    genre_ids: [12, 14, 16],
    backdrop_path: '/dWAYPAKlJi0n85P0xVEvQ2FOYLF.jpg',
    adult: false,
    overview:
      'Ashitaka, a prince of the disappearing Ainu tribe, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it. Ashitaka must find a way to bring balance to this conflict.',
    release_date: '1997-07-12',
  },
  {
    vote_count: 1007,
    id: 12477,
    video: false,
    vote_average: 8.2,
    title: 'Grave of the Fireflies',
    popularity: 1.014302,
    poster_path: '/4u1vptE8aXuzb5zauZTmikyectV.jpg',
    original_language: 'ja',
    original_title: '火垂るの墓',
    genre_ids: [16, 18, 10752],
    backdrop_path: '/sHDJzU13r5AG5OfaRkrbwmfbP7r.jpg',
    adult: false,
    overview:
      'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
    release_date: '1988-04-16',
  },
  {
    vote_count: 918,
    id: 346,
    video: false,
    vote_average: 8.2,
    title: 'Seven Samurai',
    popularity: 16.170465,
    poster_path: '/v6xrz4fr92KY1oNC3HsEvrsvR1n.jpg',
    original_language: 'ja',
    original_title: '七人の侍',
    genre_ids: [28, 18],
    backdrop_path: '/mzI1JXm8sX5fia3ifPS2jGPUh2n.jpg',
    adult: false,
    overview:
      "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food. A giant battle occurs when 40 bandits attack the village.",
    release_date: '1954-04-26',
  },
  {
    vote_count: 463,
    id: 901,
    video: false,
    vote_average: 8.2,
    title: 'City Lights',
    popularity: 13.930341,
    poster_path: '/bXNvzjULc9jrOVhGfjcc64uKZmZ.jpg',
    original_language: 'en',
    original_title: 'City Lights',
    genre_ids: [35, 18, 10749],
    backdrop_path: '/vT6ux2rdyg2kexuLisO5Ygz7pHg.jpg',
    adult: false,
    overview:
      'City Lights is the first silent film that Charlie Chaplin directed after he established himself with sound accompanied films. The film is about a penniless man who falls in love with a flower girl. The film was a great success and today is deemed a cult classic.',
    release_date: '1931-01-30',
  },
  {
    vote_count: 3238,
    id: 73,
    video: false,
    vote_average: 8.2,
    title: 'American History X',
    popularity: 19.519156,
    poster_path: '/fXepRAYOx1qC3wju7XdDGx60775.jpg',
    original_language: 'en',
    original_title: 'American History X',
    genre_ids: [18],
    backdrop_path: '/i9A0UMFg1hI2kLyCCwnmSbpT2cd.jpg',
    adult: false,
    overview:
      "Derek Vineyard is paroled after serving 3 years in prison for killing two thugs who tried to break into/steal his truck. Through his brother, Danny Vineyard's narration, we learn that before going to prison, Derek was a skinhead and the leader of a violent white supremacist gang that committed acts of racial crime throughout L.A. and his actions greatly influenced Danny. Reformed and fresh out of prison, Derek severs contact with the gang and becomes determined to keep Danny from going down the same violent path as he did.",
    release_date: '1998-10-30',
  },
  {
    vote_count: 739,
    id: 331214,
    video: false,
    vote_average: 8.2,
    title: 'Band of Brothers',
    popularity: 12.572757,
    poster_path: '/yRXTVpDRBA3983C3HjoY0SO4dV6.jpg',
    original_language: 'en',
    original_title: 'Band of Brothers',
    genre_ids: [28, 18, 10752],
    backdrop_path: '/x4cycTgAtBIy4TP0DBD2RhtKpol.jpg',
    adult: false,
    overview:
      "Drawn from interviews with survivors of Easy Company, as well as their journals and letters, Band of Brothers chronicles the experiences of these men from paratrooper training in Georgia through the end of the war. As an elite rifle company parachuting into Normandy early on D-Day morning, participants in the Battle of the Bulge, and witness to the horrors of war, the men of Easy knew extraordinary bravery and extraordinary fear - and became the stuff of legend. Based on Stephen E. Ambrose's acclaimed book of the same name.",
    release_date: '2001-09-09',
  },
  {
    vote_count: 4426,
    id: 101,
    video: false,
    vote_average: 8.2,
    title: 'Leon: The Professional',
    popularity: 23.606603,
    poster_path: '/gE8S02QUOhVnAmYu4tcrBlMTujz.jpg',
    original_language: 'fr',
    original_title: 'Léon',
    genre_ids: [53, 80, 18],
    backdrop_path: '/mGN0lH2phYfesyEVqP2xvGUaxAQ.jpg',
    adult: false,
    overview:
      'Leon, the top hit man in New York, has earned a rep as an effective "cleaner". But when his next-door neighbors are wiped out by a loose-cannon DEA agent, he becomes the unwilling custodian of 12-year-old Mathilda. Before long, Mathilda\'s thoughts turn to revenge, and she considers following in Leon\'s footsteps.',
    release_date: '1994-09-14',
  },
  {
    vote_count: 2120,
    id: 4935,
    video: false,
    vote_average: 8.2,
    title: "Howl's Moving Castle",
    popularity: 12.54996,
    poster_path: '/sVnMD28upIAlOnZNXT7OOSF5XlR.jpg',
    original_language: 'ja',
    original_title: 'ハウルの動く城',
    genre_ids: [14, 16, 12],
    backdrop_path: '/cGyqa5PxiWSsG7NSw3ufCj0JW9k.jpg',
    adult: false,
    overview:
      'When Sophie, a shy young woman, is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking home.',
    release_date: '2004-11-19',
  },
  {
    vote_count: 512,
    id: 399106,
    video: false,
    vote_average: 8.2,
    title: 'Piper',
    popularity: 11.741296,
    poster_path: '/jLRllZsubY8UWpeMyDLVXdRyEWi.jpg',
    original_language: 'en',
    original_title: 'Piper',
    genre_ids: [10751, 16],
    backdrop_path: '/w1WqcS6hT0PUWC3adG37NSUOGX5.jpg',
    adult: false,
    overview:
      'A mother bird tries to teach her little one how to find food by herself. In the process, she encounters a traumatic experience that she must overcome in order to survive.',
    release_date: '2016-06-16',
  },
  {
    vote_count: 292,
    id: 432517,
    video: false,
    vote_average: 8.2,
    title: 'Sherlock: The Final Problem',
    popularity: 9.880712,
    poster_path: '/ySiqbi1sW7imVYbtECZS0xQ3Hmj.jpg',
    original_language: 'en',
    original_title: 'Sherlock: The Final Problem',
    genre_ids: [18, 9648],
    backdrop_path: '/3nXbWFPFGvjSE5bw8G6bBLVIzow.jpg',
    adult: false,
    overview:
      'Long buried secrets finally come to light as someone has been playing a very long game indeed. Sherlock and John face their greatest ever challenge. Is the game finally over?',
    release_date: '2017-01-15',
  },
  {
    vote_count: 77,
    id: 29259,
    video: false,
    vote_average: 8.2,
    title: 'Le Trou',
    popularity: 8.880797,
    poster_path: '/pyCMEIAtMPpWTVwZTajcbCIBI3u.jpg',
    original_language: 'fr',
    original_title: 'Le Trou',
    genre_ids: [80, 18, 53],
    backdrop_path: '/v2bV7ZEJlk8cA3vbzD9u7TjGyTz.jpg',
    adult: false,
    overview:
      'An imprisoned man, awaiting trial for the attempted murder of his wife, is transferred to another cell, where his fellow prisoners are planning a jailbreak. He decides to go along with the elaborate plan, and the cellmates attempt to tunnel their way to freedom. Le Trou represents the last film of director Jacques Becker, who died shortly after its completion.',
    release_date: '1960-03-18',
  },
  {
    vote_count: 755,
    id: 265177,
    video: false,
    vote_average: 8.2,
    title: 'Mommy',
    popularity: 9.815808,
    poster_path: '/tpoaLlY0ZdVGDLToVwkGdWxLHRe.jpg',
    original_language: 'en',
    original_title: 'Mommy',
    genre_ids: [18],
    backdrop_path: '/zrknBlQbmimfVCd627VfnXwAbKn.jpg',
    adult: false,
    overview:
      'A peculiar neighbor offers hope to a recent widow who is struggling to raise a teenager who is unpredictable and, sometimes, violent.',
    release_date: '2014-05-22',
  },
  {
    vote_count: 93,
    id: 28422,
    video: false,
    vote_average: 8.2,
    title: 'Love Exposure',
    popularity: 7.447609,
    poster_path: '/f2DwUVv1sg7CjcjjyxJrNYYG0TY.jpg',
    original_language: 'ja',
    original_title: '愛のむきだし',
    genre_ids: [28, 35, 18, 10749],
    backdrop_path: '/hyrAh7Y6SvzGTsqRUye6kXZeTfz.jpg',
    adult: false,
    overview:
      "After Yu's mother dies his father, a priest, only seems to take solace in the confessions of his sons sins causing Yu to partake in various 'sinful' activities to appease him. This is a teen love story as only the Japanese could bring us, complete with up-skirt photography, cross dressing, and bloody gore.",
    release_date: '2008-11-29',
  },
  {
    vote_count: 1578,
    id: 567,
    video: false,
    vote_average: 8.2,
    title: 'Rear Window',
    popularity: 12.549027,
    poster_path: '/oXbT7vlLmZ76kWoHe5XJYuyJUgp.jpg',
    original_language: 'en',
    original_title: 'Rear Window',
    genre_ids: [18, 9648, 53],
    backdrop_path: '/s9Up9JCwmIY13XoIo3ZJ1mtMLVc.jpg',
    adult: false,
    overview:
      'Professional photographer L.B. "Jeff" Jeffries breaks his leg while getting an action shot at an auto race. Confined to his New York apartment, he spends his time looking out of the rear window observing the neighbors. He begins to suspect that a man across the courtyard may have murdered his wife. Jeff enlists the help of his high society fashion-consultant girlfriend Lisa Freemont and his visiting nurse Stella to investigate.',
    release_date: '1954-08-01',
  },
  {
    vote_count: 590,
    id: 975,
    video: false,
    vote_average: 8.2,
    title: 'Paths of Glory',
    popularity: 9.050539,
    poster_path: '/f3DEXseCs3WBtvCv9pVPCtoluuG.jpg',
    original_language: 'en',
    original_title: 'Paths of Glory',
    genre_ids: [18, 10752],
    backdrop_path: '/vSDl3hqsxxNaj0tE5ZLsTQeL0dS.jpg',
    adult: false,
    overview:
      'During World War I, commanding officer General Broulard (Adolphe Menjou) orders his subordinate, General Mireau (George Macready), to attack a German trench position, offering a promotion as an incentive. Though the mission is foolhardy to the point of suicide, Mireau commands his own subordinate, Colonel Dax (Kirk Douglas), to plan the attack. When it ends in disaster, General Mireau demands the court-martial of three random soldiers in order to save face.',
    release_date: '1957-09-18',
  },
  {
    vote_count: 209,
    id: 378064,
    video: false,
    vote_average: 8.2,
    title: 'A Silent Voice',
    popularity: 37.340882,
    poster_path: '/drlyoSKDOPnxzJFrRWGqzDsyJvR.jpg',
    original_language: 'ja',
    original_title: '聲の形',
    genre_ids: [16, 18],
    backdrop_path: '/geINneHhMbGDeDCGun0elRjVQ1Z.jpg',
    adult: false,
    overview:
      'Shouya Ishida starts bullying the new girl in class, Shouko Nishimiya, because she is deaf. But as the teasing continues, the rest of the class starts to turn on Shouya for his lack of compassion. When they leave elementary school, Shouko and Shouya do not speak to each other again... until an older, wiser Shouya, tormented by his past behaviour, decides he must see Shouko once more. He wants to atone for his sins, but is it already too late...?',
    release_date: '2016-09-17',
  },
  {
    vote_count: 8410,
    id: 122,
    video: false,
    vote_average: 8.2,
    title: 'The Lord of the Rings: The Return of the King',
    popularity: 25.17072,
    poster_path: '/uexxR7Kw1qYbZk0RYaF9Rx5ykbj.jpg',
    original_language: 'en',
    original_title: 'The Lord of the Rings: The Return of the King',
    genre_ids: [12, 14, 28],
    backdrop_path: '/8BPZO0Bf8TeAy8znF43z8soK3ys.jpg',
    adult: false,
    overview:
      "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam bring the ring closer to the heart of Mordor, the dark lord's realm.",
    release_date: '2003-12-01',
  },
  {
    vote_count: 2429,
    id: 429,
    video: false,
    vote_average: 8.2,
    title: 'The Good, the Bad and the Ugly',
    popularity: 21.277359,
    poster_path: '/wfPHdfofBD5PN96dV96a51B3Ja2.jpg',
    original_language: 'it',
    original_title: 'Il buono, il brutto, il cattivo',
    genre_ids: [37],
    backdrop_path: '/xGC2fY5KFmtuXnsuQwYQKFOLZFy.jpg',
    adult: false,
    overview:
      'While the Civil War rages between the Union and the Confederacy, three men – a quiet loner, a ruthless hit man and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
    release_date: '1966-12-23',
  },
  {
    vote_count: 5568,
    id: 77338,
    video: false,
    vote_average: 8.2,
    title: 'The Intouchables',
    popularity: 16.942477,
    poster_path: '/4mFsNQwbD0F237Tx7gAPotd0nbJ.jpg',
    original_language: 'fr',
    original_title: 'Intouchables',
    genre_ids: [18, 35],
    backdrop_path: '/ihWaJZCUIon2dXcosjQG2JHJAPN.jpg',
    adult: false,
    overview:
      'A true story of two men who should never have met – a quadriplegic aristocrat who was injured in a paragliding accident and a young man from the projects.',
    release_date: '2011-11-02',
  },
  {
    vote_count: 481,
    id: 290098,
    video: false,
    vote_average: 8.2,
    title: 'The Handmaiden',
    popularity: 16.47566,
    poster_path: '/wvzfK5QR6dGLwND8MCzWjsQWG4Q.jpg',
    original_language: 'ko',
    original_title: '아가씨',
    genre_ids: [53, 18, 10749],
    backdrop_path: '/keQhqxE9i7wNQIM3W5B0iLnjaHW.jpg',
    adult: false,
    overview:
      '1930s Korea, in the period of Japanese occupation, a new girl (Sookee) is hired as a handmaiden to a Japanese heiress (Hideko) who lives a secluded life on a large countryside estate with her domineering Uncle (Kouzuki). But the maid has a secret. She is a pickpocket recruited by a swindler posing as a Japanese Count to help him seduce the Lady to elope with him, rob her of her fortune, and lock her up in a madhouse. The plan seems to proceed according to plan until Sookee and Hideko discover some unexpected emotions.',
    release_date: '2016-06-01',
  },
  {
    vote_count: 288,
    id: 37257,
    video: false,
    vote_average: 8.2,
    title: 'Witness for the Prosecution',
    popularity: 8.714736,
    poster_path: '/heY0CCUqN4DY3X30thssZkvWZwx.jpg',
    original_language: 'en',
    original_title: 'Witness for the Prosecution',
    genre_ids: [18, 9648, 80],
    backdrop_path: '/MRTFbTBBW8uCklzye4dykWHjnz.jpg',
    adult: false,
    overview:
      'When Leonard Vole is arrested for the sensational murder of a rich, middle-aged widow, the famous Sir Wilfrid Robarts agrees to appear on his behalf. Sir Wilfrid, recovering from a near-fatal heart attack, is supposed to be on a diet of bland, civil suits – but the lure of the criminal courts is too much for him, especially when the case is so difficult.',
    release_date: '1957-12-17',
  },
  {
    vote_count: 1910,
    id: 598,
    video: false,
    vote_average: 8.2,
    title: 'City of God',
    popularity: 9.200248,
    poster_path: '/gCqnQaq8T4CfioP9uETLx9iMJF4.jpg',
    original_language: 'pt',
    original_title: 'Cidade de Deus',
    genre_ids: [18, 80],
    backdrop_path: '/k4BAPrE5WkNLvpsPsiMfu8W4Zyi.jpg',
    adult: false,
    overview:
      'Cidade de Deus is a shantytown that started during the 1960s and became one of Rio de Janeiro’s most dangerous places in the beginning of the 1980s. To tell the story of this place, the movie describes the life of various characters, all seen by the point of view of the narrator, Buscapé. Buscapé was raised in a very violent environment. Despite the feeling that all odds were against him, he finds out that life can be seen with other eyes: The eyes of an artist. By accident, he becomes a professional photographer, gaining his freedom.',
    release_date: '2002-02-05',
  },
  {
    vote_count: 776,
    id: 914,
    video: false,
    vote_average: 8.1,
    title: 'The Great Dictator',
    popularity: 9.464557,
    poster_path: '/hK2KsU0lNiYRqIrYJcC3x63dPnH.jpg',
    original_language: 'en',
    original_title: 'The Great Dictator',
    genre_ids: [35],
    backdrop_path: '/qkpsvso2neEr7v6YnyMoZtm6R9F.jpg',
    adult: false,
    overview:
      "Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution from Hynkel's regime.",
    release_date: '1940-10-15',
  },
  {
    vote_count: 216,
    id: 325553,
    video: false,
    vote_average: 8.1,
    title: 'Battlestar Galactica',
    popularity: 9.792283,
    poster_path: '/AswjNxB3PXblY7co4VJBCdUhc8v.jpg',
    original_language: 'en',
    original_title: 'Battlestar Galactica',
    genre_ids: [28, 12, 18, 878],
    backdrop_path: '/zBgF4erAECXknP6j33zzz6EMk8P.jpg',
    adult: false,
    overview:
      'After a 40-year armistice in a war between the Twelve Colonies and the Cylons, the Cylons launch a surprise nuclear attack intended to exterminate the human race. Virtually all of the population of the Twelve Colonies are wiped out.',
    release_date: '2003-12-08',
  },
  {
    vote_count: 133,
    id: 431483,
    video: false,
    vote_average: 8.1,
    title: 'Sense8: A Christmas Special',
    popularity: 6.929942,
    poster_path: '/egWvzbeQdAO3gCIN8m7ZF1hjnME.jpg',
    original_language: 'en',
    original_title: 'Sense8: A Christmas Special',
    genre_ids: [18, 9648, 878, 53],
    backdrop_path: '/mSpHS2bcBNYSOyDUta0lP7X7joj.jpg',
    adult: false,
    overview:
      "The journey continues as these eight singular hearts and minds weave in and out of each other's lives finding deeper connections, learning darker secrets about one another and struggling to identify with more than just oneself.",
    release_date: '2016-12-23',
  },
  {
    vote_count: 6098,
    id: 807,
    video: false,
    vote_average: 8.1,
    title: 'Se7en',
    popularity: 18.294538,
    poster_path: '/8zw8IL4zEPjkh8Aysdcd0FwGMb0.jpg',
    original_language: 'en',
    original_title: 'Se7en',
    genre_ids: [80, 9648, 53],
    backdrop_path: '/ba4CpvnaxvAgff2jHiaqJrVpZJ5.jpg',
    adult: false,
    overview:
      'Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer\'s mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.',
    release_date: '1995-09-22',
  },
  {
    vote_count: 129,
    id: 19542,
    video: false,
    vote_average: 8.1,
    title: 'The Red Shoes',
    popularity: 10.584975,
    poster_path: '/oyOtIdNJJO8zVwPyCtxVRxPLuHO.jpg',
    original_language: 'en',
    original_title: 'The Red Shoes',
    genre_ids: [18, 10749],
    backdrop_path: '/gf3DxP79Smp98KD6UNDsVb6GDeW.jpg',
    adult: false,
    overview:
      'In this classic drama, Vicky Page is an aspiring ballerina torn between her dedication to dance and her desire to love. While her imperious instructor, Boris Lermontov, urges to her to forget anything but ballet, Vicky begins to fall for the charming young composer Julian Craster. Eventually Vicky, under great emotional stress, must choose to pursue either her art or her romance, a decision that carries serious consequences.',
    release_date: '1948-07-20',
  },
  {
    vote_count: 3428,
    id: 629,
    video: false,
    vote_average: 8.1,
    title: 'The Usual Suspects',
    popularity: 18.059617,
    poster_path: '/jgJoRWltoS17nD5MAQ1yK2Ztefw.jpg',
    original_language: 'en',
    original_title: 'The Usual Suspects',
    genre_ids: [18, 80, 53],
    backdrop_path: '/c7e3nH3wtSBDrHRB63onrGptl6D.jpg',
    adult: false,
    overview:
      "Held in an L.A. interrogation room, Verbal Kint attempts to convince the feds that a mythic crime lord, Keyser Soze, not only exists, but was also responsible for drawing him and his four partners into a multi-million dollar heist that ended with an explosion in San Pedro harbor – leaving few survivors. Verbal lures his interrogators with an incredible story of the crime lord's almost supernatural prowess.",
    release_date: '1995-07-19',
  },
  {
    vote_count: 2909,
    id: 207,
    video: false,
    vote_average: 8.1,
    title: 'Dead Poets Society',
    popularity: 16.308139,
    poster_path: '/3Ri2GReavqSHqWemlP6HYn8i2P9.jpg',
    original_language: 'en',
    original_title: 'Dead Poets Society',
    genre_ids: [18],
    backdrop_path: '/ts8zXRgoCgGGZrTAHK6FE3cbxvu.jpg',
    adult: false,
    overview:
      'At an elite, old-fashioned boarding school in New England, a passionate English teacher inspires his students to rebel against convention and seize the potential of every day, courting the disdain of the stern headmaster.',
    release_date: '1989-06-02',
  },
  {
    vote_count: 916,
    id: 3082,
    video: false,
    vote_average: 8.1,
    title: 'Modern Times',
    popularity: 8.245795,
    poster_path: '/m4ZCx2Iwr418IGPxRfoKnpumz9X.jpg',
    original_language: 'en',
    original_title: 'Modern Times',
    genre_ids: [18, 35],
    backdrop_path: '/s58uDwuyVMqgsbmnfyrbpfF147.jpg',
    adult: false,
    overview:
      'The Tramp struggles to live in modern industrial society with the help of a young homeless woman.',
    release_date: '1936-02-05',
  },
  {
    vote_count: 130,
    id: 18491,
    video: false,
    vote_average: 8.1,
    title: 'The End of Evangelion',
    popularity: 8.562011,
    poster_path: '/5JYzfyKBwReaQ41WFhqXgOZnPWV.jpg',
    original_language: 'ja',
    original_title: '新世紀エヴァンゲリオン劇場版',
    genre_ids: [16, 18, 878],
    backdrop_path: '/vS0GsOdhNprkzYtbDBubCfYht40.jpg',
    adult: false,
    overview:
      'NERV faces a brutal attack from SEELE, but with Asuka in a coma, and Shinji in a nervous breakdown, things soon turn into the surreal. This movie provides a concurrent ending to the final two episodes of the show "Neon Genesis Evangelion".',
    release_date: '1997-07-19',
  },
  {
    vote_count: 85,
    id: 80379,
    video: false,
    vote_average: 8.1,
    title: 'Louis C.K.: Live at the Beacon Theater',
    popularity: 5.580189,
    poster_path: '/7IB9s2Oyjr6VVYXm1vDazQgdGFF.jpg',
    original_language: 'en',
    original_title: 'Louis C.K.: Live at the Beacon Theater',
    genre_ids: [35],
    backdrop_path: '/5MmUcWuIeo10NczbmuQ8ftPDd6X.jpg',
    adult: false,
    overview:
      'Recorded November 10th, 2011 as part of the New York Comedy Festival, and only available for purchase online, Louis C.K. follows up his 2010 concert film Hilarious with a new hour’s worth of shrewdly observed and periodically profane material. He starts with making his own kind of please-turn-off-your-cell-phone announcement, as well as a warning not to text or tweet during the show: “Just live your life,” he asks. Whether he’s talking about a unique way to drop a rental car off at an airport or describing why a man in his 40s should not smoke dope, it’s terrific, humane, carried-to-crazed-extremes stuff.',
    release_date: '2011-12-10',
  },
  {
    vote_count: 136,
    id: 992,
    video: false,
    vote_average: 8.1,
    title: 'Sherlock, Jr.',
    popularity: 9.541632,
    poster_path: '/1G9r3rqtbFAQuyWKOZm4Y5J5s7Q.jpg',
    original_language: 'en',
    original_title: 'Sherlock, Jr.',
    genre_ids: [14, 18, 35, 9648],
    backdrop_path: '/l3RiIjaN1peXQ2lAwnpF33Xb5R0.jpg',
    adult: false,
    overview:
      "A film projectionist longs to be a detective, and puts his meagre skills to work when he is framed by a rival for stealing his girlfriend's father's pocketwatch.",
    release_date: '1924-04-21',
  },
  {
    vote_count: 102,
    id: 14696,
    video: false,
    vote_average: 8.1,
    title: 'Ugetsu',
    popularity: 7.772465,
    poster_path: '/gF4PQYOufm5WcQREHegJI7PjsDy.jpg',
    original_language: 'ja',
    original_title: '雨月物語',
    genre_ids: [14, 18, 9648],
    backdrop_path: '/3n4vhUJMwWGwG49G1ofTkQdFc1A.jpg',
    adult: false,
    overview:
      'In the civil wars of 16th century Japan, two ambitious peasants in Nakanogo want to make their fortunes. The potter Genjuro intends to sell his wares for vast profits in the local city, Omizo, while his brother-in-law Tobei wishes to become a samurai. A respected sage warns them against seeking profit in times of war but his advice goes unheeded, and their insistency leads to the ruin of their families.',
    release_date: '1953-03-26',
  },
  {
    vote_count: 429,
    id: 411088,
    video: false,
    vote_average: 8.1,
    title: 'The Invisible Guest',
    popularity: 17.615575,
    poster_path: '/fptnZJbLzKUHeNlYrAynbyoL5YJ.jpg',
    original_language: 'es',
    original_title: 'Contratiempo',
    genre_ids: [9648, 80, 53],
    backdrop_path: '/6xCeSDyXr9tC1jdBsdx3QJEQuSc.jpg',
    adult: false,
    overview:
      '"The Invisible Guest” turns on a young businessman who wakes up in a hotel room locked from the inside with the dead body of his lover next to him. He hires a prestigious lawyer, and over one night they work together to clarify what happened in a frenetic race against time.',
    release_date: '2016-12-15',
  },
  {
    vote_count: 117,
    id: 24382,
    video: false,
    vote_average: 8.1,
    title: 'Big Deal on Madonna Street',
    popularity: 6.297221,
    poster_path: '/x09KfYUEBHoO2QB7KHtYGpVdxtj.jpg',
    original_language: 'it',
    original_title: 'I soliti ignoti',
    genre_ids: [80, 35],
    backdrop_path: '/t9O7rSz6hlXF3fxiimFqruJ1GQ5.jpg',
    adult: false,
    overview:
      'Peppe, formerly a boxer, organizes the break-in of a pawnshop. Tiberio, an unemployed photographer, Mario, a receiver, the Sicilian Michele and Capannelle, an ex-jockey, are the other members of the gang. Though they are advised by Dante, a retired burglar, the task is not so easy...',
    release_date: '1958-06-06',
  },
  {
    vote_count: 14413,
    id: 27205,
    video: false,
    vote_average: 8.1,
    title: 'Inception',
    popularity: 32.04312,
    poster_path: '/qmDpIHrmpJINaRKAfWQfftjCdyi.jpg',
    original_language: 'en',
    original_title: 'Inception',
    genre_ids: [28, 53, 878, 9648, 12],
    backdrop_path: '/s2bT29y0ngXxxu2IA8AOzzXTRhd.jpg',
    adult: false,
    overview:
      'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
    release_date: '2010-07-14',
  },
  {
    vote_count: 95,
    id: 92060,
    video: false,
    vote_average: 8.1,
    title: "Michael Jackson's Thriller",
    popularity: 5.566053,
    poster_path: '/puLSRxaG8MweynoRt8wZS8ZXZRM.jpg',
    original_language: 'en',
    original_title: "Michael Jackson's Thriller",
    genre_ids: [27, 10402],
    backdrop_path: '/kEGls1NMhHUzL92meK9Cm53Qm2N.jpg',
    adult: false,
    overview:
      'A night at the movies turns into a nightmare when Michael and his date are attacked by a hoard of bloody-thirsty zombies.',
    release_date: '1983-12-02',
  },
  {
    vote_count: 11489,
    id: 157336,
    video: false,
    vote_average: 8.1,
    title: 'Interstellar',
    popularity: 37.941237,
    poster_path: '/nBNZadXqJSdt05SHLqgT0HuC5Gm.jpg',
    original_language: 'en',
    original_title: 'Interstellar',
    genre_ids: [12, 18, 878],
    backdrop_path: '/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg',
    adult: false,
    overview:
      'Interstellar chronicles the adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    release_date: '2014-11-05',
  },
  {
    vote_count: 94,
    id: 24188,
    video: false,
    vote_average: 8.1,
    title: 'Il Sorpasso',
    popularity: 5.821727,
    poster_path: '/cnMOaDouZek6l7BcydVBrBlWegi.jpg',
    original_language: 'it',
    original_title: 'Il sorpasso',
    genre_ids: [18, 35],
    backdrop_path: '/sNjjEyEX86INsiFCEzvLyGEWJSN.jpg',
    adult: false,
    overview:
      'Roberto, a shy law student in Rome, meets Bruno, a forty-year-old exuberant, capricious man, who takes him for a drive through the Roman and Tuscany countries in the summer.',
    release_date: '1962-12-04',
  },
  {
    vote_count: 2909,
    id: 264644,
    video: false,
    vote_average: 8.1,
    title: 'Room',
    popularity: 12.752821,
    poster_path: '/eqFckcHuFCT1FrzLOAvXBb4jHwq.jpg',
    original_language: 'en',
    original_title: 'Room',
    genre_ids: [18, 53],
    backdrop_path: '/tBhp8MGaiL3BXpPCSl5xY397sGH.jpg',
    adult: false,
    overview:
      'Jack is a young boy of 5 years old who has lived all his life in one room. He believes everything within it are the only real things in the world. But what will happen when his Ma suddenly tells him that there are other things outside of Room?',
    release_date: '2015-10-16',
  },
  {
    vote_count: 4697,
    id: 274,
    video: false,
    vote_average: 8.1,
    title: 'The Silence of the Lambs',
    popularity: 6.206836,
    poster_path: '/qjAyTj2BSth1EQ89vNfo0JYVPFN.jpg',
    original_language: 'en',
    original_title: 'The Silence of the Lambs',
    genre_ids: [80, 18, 53],
    backdrop_path: '/1ewiz2BOytcyE90ozbaiDDZn8ma.jpg',
    adult: false,
    overview:
      'FBI trainee, Clarice Starling ventures into a maximum-security asylum to pick the diseased brain of Hannibal Lecter, a psychiatrist turned homicidal cannibal. Starling needs clues to help her capture a serial killer. but her Faustian relationship with Lecter soon leads to his escape, and now two deranged killers are on the loose.',
    release_date: '1991-02-01',
  },
  {
    vote_count: 134,
    id: 18438,
    video: false,
    vote_average: 8.1,
    title: 'Castaway on the Moon',
    popularity: 6.586641,
    poster_path: '/bqGgSOtz7d2TnDQEANwCZGmSaT2.jpg',
    original_language: 'ko',
    original_title: '김씨 표류기',
    genre_ids: [18, 35, 10749],
    backdrop_path: '/fBKXwJxK1c1WLI6NrYOmL5WEE3G.jpg',
    adult: false,
    overview:
      'Mr. Kim is jobless, lost in debt and has been dumped by his girlfriend. He decides to end it all by jumping into the Han River - only to find himself washed up on a small, mid-river island. He soon abandons thoughts of suicide or rescue and begins a new life as a castaway. His antics catch the attention of a young woman whose apartment overlooks the river. Her discovery changes both their lives.',
    release_date: '2009-05-14',
  },
  {
    vote_count: 179,
    id: 25237,
    video: false,
    vote_average: 8.1,
    title: 'Come and See',
    popularity: 9.399356,
    poster_path: '/oBR0fDwrtScFfecTPAg10potlzQ.jpg',
    original_language: 'ru',
    original_title: 'Иди и смотри',
    genre_ids: [18, 36, 10752],
    backdrop_path: '/1RKpaOeY60gCNbkW2xGBrXYkZUg.jpg',
    adult: false,
    overview:
      "The invasion of a village in Byelorussia by German forces sends young Florya into the forest to join the weary Resistance fighters, against his family's wishes. There he meets a girl, Glasha, who accompanies him back to his village. On returning home, Florya finds his family and fellow peasants massacred. His continued survival amidst the brutal debris of war becomes increasingly nightmarish, a battle between despair and hope.",
    release_date: '1985-07-01',
  },
  {
    vote_count: 111,
    id: 92321,
    video: false,
    vote_average: 8.1,
    title: 'Hotarubi no Mori e',
    popularity: 1.007507,
    poster_path: '/mDqzHV8UXWWNpZkoAbKmKX1ZxEE.jpg',
    original_language: 'ja',
    original_title: '蛍火の杜へ',
    genre_ids: [10749, 16, 14],
    backdrop_path: '/nD8NF5gt5sQLxDTOpFdIhrJBR8L.jpg',
    adult: false,
    overview:
      'One hot summer day a little girl gets lost in an enchanted forest of the mountain god where spirits reside. A young boy appears before her, but she cannot touch him for fear of making him disappear. And so a wondrous adventure awaits...',
    release_date: '2011-09-17',
  },
  {
    vote_count: 4319,
    id: 77,
    video: false,
    vote_average: 8.1,
    title: 'Memento',
    popularity: 16.606103,
    poster_path: '/fQMSaP88cf1nz4qwuNEEFtazuDM.jpg',
    original_language: 'en',
    original_title: 'Memento',
    genre_ids: [9648, 53],
    backdrop_path: '/oBUznaSdjkY3HtQUzAxgdIZqh4w.jpg',
    adult: false,
    overview:
      "Suffering short-term memory loss after a head injury, Leonard Shelby embarks on a grim quest to find the lowlife who murdered his wife in this gritty, complex thriller that packs more knots than a hangman's noose. To carry out his plan, Shelby snaps Polaroids of people and places, jotting down contextual notes on the backs of photos to aid in his search and jog his memory. He even tattoos his own body in a desperate bid to remember.",
    release_date: '2000-10-11',
  },
  {
    vote_count: 516,
    id: 284,
    video: false,
    vote_average: 8.1,
    title: 'The Apartment',
    popularity: 10.200895,
    poster_path: '/6OH3HlplEGoGjqeqRmWaVBGqbav.jpg',
    original_language: 'en',
    original_title: 'The Apartment',
    genre_ids: [35, 18, 10749],
    backdrop_path: '/vF4d4hAKMcrDE4Y6zLwUSijp32g.jpg',
    adult: false,
    overview:
      "Bud Baxter is a minor clerk in a huge New York insurance company, until he discovers a quick way to climb the corporate ladder. He lends out his apartment to the executives as a place to take their mistresses. Although he often has to deal with the aftermath of their visits, one night he's left with a major problem to solve.",
    release_date: '1960-06-15',
  },
  {
    vote_count: 272,
    id: 237791,
    video: false,
    vote_average: 8.1,
    title: 'The Way He Looks',
    popularity: 8.063745,
    poster_path: '/oAPCsQiWV6YUd0Gt62BOwb8aSth.jpg',
    original_language: 'pt',
    original_title: 'Hoje Eu Quero Voltar Sozinho',
    genre_ids: [18, 10749],
    backdrop_path: '/qLxZZuENWJiBrmOD17Wf3qAHGQb.jpg',
    adult: false,
    overview:
      'Leonardo is a blind teenager dealing with an overprotective mother while trying to live a more independent life. To the disappointment of his best friend, Giovana, he plans to go on an exchange program abroad. When Gabriel, a new student in town, arrives at their classroom, new feelings blossom in Leonardo making him question his plans.',
    release_date: '2014-03-28',
  },
  {
    vote_count: 1185,
    id: 335,
    video: false,
    vote_average: 8.1,
    title: 'Once Upon a Time in the West',
    popularity: 14.655118,
    poster_path: '/rVAHRtAMhV8QVXQMQ8NxNbZXCDp.jpg',
    original_language: 'it',
    original_title: "C'era una volta il West",
    genre_ids: [37],
    backdrop_path: '/sNaQWTsQFfdhjKweXbgjSHKZ8YS.jpg',
    adult: false,
    overview:
      'This classic western masterpiece is an epic film about a widow whose land and life are in danger as the railroad is getting closer and closer to taking them over. A mysterious harmonica player joins forces with a desperado to protect the woman and her land.',
    release_date: '1968-12-21',
  },
  {
    vote_count: 574,
    id: 10376,
    video: false,
    vote_average: 8.1,
    title: 'The Legend of 1900',
    popularity: 8.989514,
    poster_path: '/wss1PkvHD2cYH6lu5mSa2MgGoi.jpg',
    original_language: 'it',
    original_title: "La leggenda del pianista sull'oceano",
    genre_ids: [14],
    backdrop_path: '/g95aipBRguk1lFwpAU7FJ4Z9cws.jpg',
    adult: false,
    overview:
      'The story of a virtuoso piano player who lives his entire life aboard an ocean liner. Born and raised on the ship, 1900 (Tim Roth) learned about the outside world through interactions with passengers, never setting foot on land, even for the love of his life. Years later, the ship may be destroyed, and a former band member fears that 1900 may still be aboard, willing to go down with the ship.',
    release_date: '1998-10-28',
  },
  {
    vote_count: 4091,
    id: 694,
    video: false,
    vote_average: 8.1,
    title: 'The Shining',
    popularity: 22.590836,
    poster_path: '/9fgh3Ns1iRzlQNYuJyK0ARQZU7w.jpg',
    original_language: 'en',
    original_title: 'The Shining',
    genre_ids: [27, 53],
    backdrop_path: '/h4DcDCOkQBENWBJZjNlPv3adQfM.jpg',
    adult: false,
    overview:
      "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, along with his wife Wendy and their son Danny, must live isolated from the rest of the world for the winter. But they aren't prepared for the madness that lurks within.",
    release_date: '1980-05-22',
  },
  {
    vote_count: 170,
    id: 393729,
    video: false,
    vote_average: 8.1,
    title: 'Divines',
    popularity: 8.813958,
    poster_path: '/yTZw4CdK0cWac9ugayJLv09N4op.jpg',
    original_language: 'fr',
    original_title: 'Divines',
    genre_ids: [18],
    backdrop_path: '/hvRMQT6neHXApaJwLnMWMheTlpk.jpg',
    adult: false,
    overview:
      'In a ghetto where religion and drug trafficking rub shoulders, Dounia has a lust for power and success. Supported by Maimouna, her best friend, she decides to follow in the footsteps of Rebecca, a respected dealer. But her encounter with Djigui, a young, disturbingly sensual dancer, throws her off course.',
    release_date: '2016-08-31',
  },
  {
    vote_count: 3949,
    id: 500,
    video: false,
    vote_average: 8.1,
    title: 'Reservoir Dogs',
    popularity: 17.305167,
    poster_path: '/tB2ITHg556e7aTV6cqQqVAXkdxN.jpg',
    original_language: 'en',
    original_title: 'Reservoir Dogs',
    genre_ids: [80, 53],
    backdrop_path: '/gjOiE5EYH5sqcJYlSDZnVWRMgNV.jpg',
    adult: false,
    overview:
      'A botched robbery indicates a police informant, and the pressure mounts in the aftermath at a warehouse. Crime begets violence as the survivors -- veteran Mr. White, newcomer Mr. Orange, psychopathic parolee Mr. Blonde, bickering weasel Mr. Pink and Nice Guy Eddie -- unravel.',
    release_date: '1992-09-02',
  },
  {
    vote_count: 504,
    id: 110420,
    video: false,
    vote_average: 8.1,
    title: 'Wolf Children',
    popularity: 8.06535,
    poster_path: '/rDMxjCYEVnvLC4nsBpB6wjL0LDy.jpg',
    original_language: 'ja',
    original_title: 'おおかみこどもの雨と雪',
    genre_ids: [16, 18, 10751, 14],
    backdrop_path: '/1Y66fi0srOb0ijAOg069DXriD3S.jpg',
    adult: false,
    overview:
      'Hana, a nineteen-year-old college student, falls in love with a man only for him to reveal his secret; he is a Wolf Man. Eventually the couple bear two children together; a son and daughter they name Ame and Yuki who both inherit the ability to transform into wolves from their father. When the man Hana fell in love with suddenly dies, she makes the decision to move to a rural town isolated from society to continue raising the children in protection.',
    release_date: '2012-07-21',
  },
  {
    vote_count: 2725,
    id: 103,
    video: false,
    vote_average: 8.1,
    title: 'Taxi Driver',
    popularity: 14.431484,
    poster_path: '/yxq4pk1xGmro8tQABuQIrWrvdaE.jpg',
    original_language: 'en',
    original_title: 'Taxi Driver',
    genre_ids: [80, 18],
    backdrop_path: '/hjmJKAVoZ3n2KWbKgasbfdugwhu.jpg',
    adult: false,
    overview:
      'A mentally unstable Vietnam War veteran works as a night-time taxi driver in New York City where the perceived decadence and sleaze feeds his urge for violent action, attempting to save a preadolescent prostitute in the process.',
    release_date: '1976-02-07',
  },
  {
    vote_count: 415,
    id: 5156,
    video: false,
    vote_average: 8.1,
    title: 'Bicycle Thieves',
    popularity: 12.011789,
    poster_path: '/8ipMMbjgAA9M4wpoPc9yxFEiIeA.jpg',
    original_language: 'it',
    original_title: 'Ladri di biciclette',
    genre_ids: [18],
    backdrop_path: '/vyz8ZJpATpxWCvYe5caZyzdn9Zq.jpg',
    adult: false,
    overview:
      "Antonio, an unemployed man in the depressed post-WWII economy of Italy, at last finds a good job hanging up posters, the only requirement for which is that he must have his own bicycle. When Antonio's bicycle is stolen, he and his son are forced to walk the streets of Rome in search of it, or else face ruin.",
    release_date: '1948-11-24',
  },
  {
    vote_count: 6967,
    id: 11,
    video: false,
    vote_average: 8.1,
    title: 'Star Wars',
    popularity: 37.597078,
    poster_path: '/btTdmkgIvOi0FFip1sPuZI2oQG6.jpg',
    original_language: 'en',
    original_title: 'Star Wars',
    genre_ids: [12, 28, 878],
    backdrop_path: '/c4zJK1mowcps3wvdrm31knxhur2.jpg',
    adult: false,
    overview:
      'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.',
    release_date: '1977-05-25',
  },
  {
    vote_count: 92,
    id: 11659,
    video: false,
    vote_average: 8.1,
    title: 'The Best of Youth',
    popularity: 8.859924,
    poster_path: '/fWi5OVdODBYsNXZTmVbvV1ROMhl.jpg',
    original_language: 'it',
    original_title: 'La Meglio Gioventú',
    genre_ids: [18],
    backdrop_path: '/2Qn2Aq3uLfgQfO8XZGyinxreD52.jpg',
    adult: false,
    overview:
      "Spanning four decades, from the chaotic 1960s to the present, director Marco Tullio Giordana's passionate epic 'La Meglio Gioventu' follows two Italian brothers through some of the most tumultuous events of recent Italian history.",
    release_date: '2003-05-19',
  },
  {
    vote_count: 427,
    id: 110416,
    video: false,
    vote_average: 8.1,
    title: 'Song of the Sea',
    popularity: 8.786555,
    poster_path: '/uvNv23Arf2ZYtimiStSB2c1DAEX.jpg',
    original_language: 'en',
    original_title: 'Song of the Sea',
    genre_ids: [10751, 16, 14],
    backdrop_path: '/lYC3zeM5ur5un18lNPK4J4B8hYR.jpg',
    adult: false,
    overview:
      'The story of the last Seal Child’s journey home. After their mother’s disappearance, Ben and Saoirse are sent to live with Granny in the city. When they resolve to return to their home by the sea, their journey becomes a race against time as they are drawn into a world Ben knows only from his mother’s folktales. But this is no bedtime story; these fairy folk have been in our world far too long. It soon becomes clear to Ben that Saoirse is the key to their survival.',
    release_date: '2014-09-06',
  },
  {
    vote_count: 9090,
    id: 120,
    video: false,
    vote_average: 8.1,
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    popularity: 33.220778,
    poster_path: '/bxVxZb5O9OxCO0oRUNdCnpy9NST.jpg',
    original_language: 'en',
    original_title: 'The Lord of the Rings: The Fellowship of the Ring',
    genre_ids: [12, 14, 28],
    backdrop_path: '/pIUvQ9Ed35wlWhY2oU6OmwEsmzG.jpg',
    adult: false,
    overview:
      'Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.',
    release_date: '2001-12-18',
  },
  {
    vote_count: 377,
    id: 654,
    video: false,
    vote_average: 8.1,
    title: 'On the Waterfront',
    popularity: 10.167865,
    poster_path: '/2AKM5RxGoerG5v1x4TWu36MDxqT.jpg',
    original_language: 'en',
    original_title: 'On the Waterfront',
    genre_ids: [80, 18],
    backdrop_path: '/zXp2ydvhO9qGzpIsb1CWeKnn5yg.jpg',
    adult: false,
    overview:
      "Terry Malloy dreams about being a prize fighter, while tending his pigeons and running errands at the docks for Johnny Friendly, the corrupt boss of the dockers union. Terry witnesses a murder by two of Johnny's thugs, and later meets the dead man's sister and feels responsible for his death. She introduces him to Father Barry, who tries to force him to provide information for the courts that will smash the dock racketeers.",
    release_date: '1954-06-22',
  },
  {
    vote_count: 141,
    id: 895,
    video: false,
    vote_average: 8.1,
    title: 'Andrei Rublev',
    popularity: 6.345439,
    poster_path: '/nmSf6Kc0J9VUi9SDDkx0D5dKHLK.jpg',
    original_language: 'ru',
    original_title: 'Андрей Рублёв',
    genre_ids: [18, 36],
    backdrop_path: '/8iIVnCOTn3QcVicgnrcLrnm3JBS.jpg',
    adult: false,
    overview:
      'An expansive Russian drama, this film focuses on the life of revered religious icon painter Andrei Rublev. Drifting from place to place in a tumultuous era, the peace-seeking monk eventually gains a reputation for his art. But after Rublev witnesses a brutal battle and unintentionally becomes involved, he takes a vow of silence and spends time away from his work. As he begins to ease his troubled soul, he takes steps towards becoming a painter once again.',
    release_date: '1966-12-16',
  },
  {
    vote_count: 2182,
    id: 28,
    video: false,
    vote_average: 8.1,
    title: 'Apocalypse Now',
    popularity: 15.137068,
    poster_path: '/jcvJ2xcVWU9Wh0hZAxcs103s8nN.jpg',
    original_language: 'en',
    original_title: 'Apocalypse Now',
    genre_ids: [18, 10752],
    backdrop_path: '/k91Dag8AZbhjIJqrtf7F1bQnGPg.jpg',
    adult: false,
    overview:
      'At the height of the Vietnam war, Captain Benjamin Willard is sent on a dangerous mission that, officially, "does not exist, nor will it ever exist." His goal is to locate - and eliminate - a mysterious Green Beret Colonel named Walter Kurtz, who has been leading his personal army on illegal guerrilla missions into enemy territory.',
    release_date: '1979-08-15',
  },
  {
    vote_count: 92,
    id: 81481,
    video: false,
    vote_average: 8.1,
    title: 'Silenced',
    popularity: 5.936466,
    poster_path: '/5cRQ516LBcW4nPKxTX3F8u7otSZ.jpg',
    original_language: 'ko',
    original_title: '도가니',
    genre_ids: [18],
    backdrop_path: '/vi8Td5ziicumFdPMUxA3Sd7j4Mz.jpg',
    adult: false,
    overview:
      'Based on actual events that took place at Gwangju Inhwa School for the hearing-impaired, where young deaf students were the victims of repeated sexual assaults by faculty members over a period of five years in the early 2000s.',
    release_date: '2011-09-22',
  },
  {
    vote_count: 1990,
    id: 423,
    video: false,
    vote_average: 8.1,
    title: 'The Pianist',
    popularity: 13.9749,
    poster_path: '/iunmxWkOi7Vk17Ob3G2HwwjgHsr.jpg',
    original_language: 'en',
    original_title: 'The Pianist',
    genre_ids: [18, 10752],
    backdrop_path: '/xUR95VFV1UTyzS1C8Lj06hi2n2M.jpg',
    adult: false,
    overview:
      'The Pianist is a film adapted from the biography of Wladyslaw Szpilman. A Jewish-Polish pianist who during the second world war lived and hid miraculously in Warsaw after having gone through a terrible tragedy. A film from Roman Polanski.',
    release_date: '2002-09-24',
  },
  {
    vote_count: 76,
    id: 160885,
    video: false,
    vote_average: 8.1,
    title: 'Tel chi el telùn',
    popularity: 5.368415,
    poster_path: '/hfVkk9FOJJkVps1ahdun4mq7m4J.jpg',
    original_language: 'it',
    original_title: 'Tel chi el telùn',
    genre_ids: [35],
    backdrop_path: '/kBNMqlNh1sskJixIDdhbLZnBBjt.jpg',
    adult: false,
    overview: '',
    release_date: '2009-03-01',
  },
  {
    vote_count: 1214,
    id: 426,
    video: false,
    vote_average: 8.1,
    title: 'Vertigo',
    popularity: 9.323628,
    poster_path: '/obhM86qyv8RsE69XSMTtT9FdE0b.jpg',
    original_language: 'en',
    original_title: 'Vertigo',
    genre_ids: [9648, 10749, 53],
    backdrop_path: '/idbDJjoTQxLejUUkDJ0FNEim6FB.jpg',
    adult: false,
    overview:
      "A retired San Francisco detective suffering from acrophobia investigates the strange activities of an old friend's wife, all the while becoming dangerously obsessed with her.",
    release_date: '1958-05-09',
  },
];

const insertData = genres.map(element => ({
  genre_id: element.id,
  genre: element.name,
}));

const topMovies = movies.map(element => ({
  api_movie_id: element.id,
  adult: element.adult,
  overview: element.overview,
  title: element.title,
  vote_average: element.vote_average,
  poster_path: element.poster_path,
  release_date: element.release_date,
  vote_count: element.vote_count,
  popularity: element.popularity,
  original_language: element.original_language,
}));


knex('genres')
  .insert(insertData)
  .then((rows) => {
    console.log(rows);
  })
  .catch((err) => {
    console.log(err);
  });


const movieGenre = [];
movies.forEach((element, index) => {
  element.genre_ids.forEach((id) => {
    movieGenre.push({
      top_movie_id: index + 1,
      genre_id: id,
    });
  });
});

knex('top_movies')
  .insert(topMovies)
  .then((result) => {
    console.log(result);
    return knex('movie_genre').insert(movieGenre);
  })
  .then((result) => {
    console.log(result);
  })
  .catch((err) => {
    console.log(err);
  });
